#!/bin/bash
# This script ensures the Rust toolchain is available and then runs the setup application.

set -e

# Check if cargo is installed
if ! command -v cargo &> /dev/null
then
    echo "Rust and Cargo are not installed. Please install them to continue."
    echo "You can find installation instructions at: https://www.rust-lang.org/tools/install"
    exit 1
fi


# check if fastly cli is installed
if ! command -v fastly &> /dev/null
then
    echo "Fastly CLI is not installed. Please install it to continue."
    echo "You can find installation instructions at: https://developer.fastly.com/learning/tools/cli/"
    exit 1
fi


